server {
    # SSL configuration
    listen 443 ssl;
    listen [::]:443 ssl;

    # Your domain name from the .env will point here
    server_name sasakuya.42.fr;

    # SSL Certificates (we will generate these in the Dockerfile)
    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;

    # Encryption protocols (Subject requirement: TLSv1.2 or TLSv1.3 only)
    ssl_protocols TLSv1.2 TLSv1.3;

    # Root directory and index files
    root /var/www/html;
    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    # Pass PHP scripts to the WordPress container via FastCGI
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
